# Autogenerated by create_merge_imports.py
# Do not modify by hand - this file is built
# automatically during the build process
# by build.bat!

import mergers.merge_alarms
import mergers.merge_calfactors
import mergers.merge_emailsettings
import mergers.merge_lines
import mergers.merge_loggersettings
import mergers.merge_recipes
import mergers.merge_reportsettings
import mergers.merge_sysvars
