
import os
here = os.path.dirname(__file__)
mergers = os.path.join(here, 'src', 'merge', 'mergers')
mfs = [f for f in os.listdir(mergers) if f.startswith("merge_")]
out = "src\\merge\\merge_handlers.py"
ofp = os.path.join(here, out)
with open(ofp, 'w') as f:

    f.write("# Autogenerated by create_merge_imports.py\n")
    f.write("# Do not modify by hand - this file is built\n")
    f.write("# automatically during the build process\n")
    f.write("# by build.bat!\n")
    f.write("\n")
    for m in mfs:
        m = os.path.splitext(m)[0]
        f.write("import mergers.%s\n"%m)